### PR TITLE
Rinkeby: deploy hatch.aragonpm.eth registry

### PR DESCRIPTION
**Pull request by izqui**
TODO:

- [x] Add to deployments main page

### CODE REVIEW

**Comment by sohkai** [comment]
We should also do this for staging when this is finalized 😄

**Comment by 0xGabi** [comment]
Does make sense to have this registry on aragen as well? 🤔

**Comment by sohkai** [comment]
> Does make sense to have this registry on aragen as well? 🤔

Yes!

**Comment by sohkai** [comment]
`hatch` is now also deployed to staging, although no one has permission to create packages on it yet.

**Pull request merged**
